"""Initial

Revision ID: 0e23de6fefc1
Revises: 
Create Date: 2026-03-11 20:21:27.321343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e23de6fefc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disciplines'))
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('group_discipline_link',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name=op.f('fk_group_discipline_link_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_discipline_link_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'discipline_id', name=op.f('pk_group_discipline_link'))
    )
    op.create_table('student_group_link',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_student_group_link_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_group_link_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'group_id', name=op.f('pk_student_group_link'))
    )
    op.create_table('teacher_discipline_link',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name=op.f('fk_teacher_discipline_link_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_discipline_link_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'discipline_id', name=op.f('pk_teacher_discipline_link'))
    )
    op.create_table('tests',
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('questions_to_show', sa.Integer(), nullable=True),
    sa.Column('grading_method', sa.Enum('AUTO', 'MANUAL', 'MIXED', name='gradingmethod'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_tests_creator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name=op.f('fk_tests_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tests'))
    )
    op.create_table('questions',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TEXT_ANSWER', name='questiontype'), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('allow_partial_credit', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', name='mediatype'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_questions_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('test_attempts',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', name='attemptstatus'), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('confidence_index', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_test_attempts_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_attempts_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_attempts'))
    )
    op.create_table('answer_options',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answer_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_options'))
    )
    op.create_table('proctoring_events',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('TAB_SWITCH', 'COPY_PASTE', 'MOUSE_LEAVE', 'CONNECTION_LOST', name='proctoringaction'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], name=op.f('fk_proctoring_events_attempt_id_test_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proctoring_events'))
    )
    with op.batch_alter_table('proctoring_events', schema=None) as batch_op:
        batch_op.create_index('ix_proctoring_event_attempt_timestamp', ['attempt_id', 'timestamp'], unique=False)

    op.create_table('student_answers',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('awarded_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], name=op.f('fk_student_answers_attempt_id_test_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_student_answers_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question')
    )
    op.create_table('student_answer_option_link',
    sa.Column('student_answer_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['answer_options.id'], name=op.f('fk_student_answer_option_link_option_id_answer_options'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_answer_id'], ['student_answers.id'], name=op.f('fk_student_answer_option_link_student_answer_id_student_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_answer_id', 'option_id', name=op.f('pk_student_answer_option_link'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_answer_option_link')
    op.drop_table('student_answers')
    with op.batch_alter_table('proctoring_events', schema=None) as batch_op:
        batch_op.drop_index('ix_proctoring_event_attempt_timestamp')

    op.drop_table('proctoring_events')
    op.drop_table('answer_options')
    op.drop_table('test_attempts')
    op.drop_table('questions')
    op.drop_table('tests')
    op.drop_table('teacher_discipline_link')
    op.drop_table('student_group_link')
    op.drop_table('group_discipline_link')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
