"""add test_student_association table

Revision ID: b4dd31dafba8
Revises: af0f511230da
Create Date: 2026-03-30 16:42:38.949519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dd31dafba8'
down_revision: Union[str, Sequence[str], None] = 'af0f511230da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_student_association',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_test_student_association_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_student_association_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'student_id', name=op.f('pk_test_student_association'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_student_association')
    # ### end Alembic commands ###
