"""add test_media table

Revision ID: af0f511230da
Revises: 0e23de6fefc1
Create Date: 2026-03-25 15:17:03.509510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0f511230da'
down_revision: Union[str, Sequence[str], None] = '0e23de6fefc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_media',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', name='mediatype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_media_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_media'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_media')
    # ### end Alembic commands ###
